Dev
stefandjokovic88/week-2-profile-card pull request #1
Opened 2021-09-13 14:59 UTC by stefandjokovic88

2021-09-14 08:13 UTC, chomii82 commented on index.html
> +    <div class="container">
Vidim da container ima visinu 0. Proveri samo o cemu se radi.

2021-09-14 08:13 UTC, sbozic85 commented on style.css
> +@media screen and (max-width: 375px) {
Stranica se ne prikazuje lepo na telefonima sirine 375px i manje, obrati paznju na sirinu kartice u odnosu na sirinu cele stranice i ispravi to

2021-09-14 08:16 UTC, sbozic85 requested changes
Ispravi ovo sto smo ti Milan i ja napisali i napravi novi commit

2021-09-15 06:49 UTC, sbozic85 commented on style.css
> +.card .picture p span span {
Nema razloga na ovako maloj stranici da imas ovakav CSS selektor. CSS selektori treba da su u startu sto slabiji, npr. jedna klasa, pa onda ako treba da modifikujes nesto pravis jaci selektor. Ovo ti se ponavlja na vise mesta, moja sugestija je da ubuduce to pises drugacije

2021-09-15 06:50 UTC, sbozic85 requested changes
Jos uvek ne izgleda dobro na malim ekranima. Pogledaj dizajn i ispravi

2021-09-16 09:16 UTC, sbozic85 approved these changes
Sugestija za ubuduce je da koristis CSS promenljive i da stranica treba da izgleda dobro na svim sirinama ekrana, znaci od nekih 320px pa sve do velikih monitora

2021-09-16 09:16 UTC, merged